" This file contains spacemacs keybindings
source ./intelli-space/spacemacs/default_set.vim
source ./intelli-space/spacemacs/applications.vim
source ./intelli-space/spacemacs/basic.vim
source ./intelli-space/spacemacs/buffers.vim
source ./intelli-space/spacemacs/compile-comments.vim
source ./intelli-space/spacemacs/errors.vim
source ./intelli-space/spacemacs/files.vim
source ./intelli-space/spacemacs/git-vcs.vim
source ./intelli-space/spacemacs/help.vim
source ./intelli-space/spacemacs/insertion.vim
source ./intelli-space/spacemacs/jump-join-split.vim
source ./intelli-space/spacemacs/narrow-numbers.vim
source ./intelli-space/spacemacs/projects.vim
source ./intelli-space/spacemacs/toggles.vim
source ./intelli-space/spacemacs/quit.vim
source ./intelli-space/spacemacs/registers-rings-resume.vim
source ./intelli-space/spacemacs/search-symbol.vim
source ./intelli-space/spacemacs/toggles.vim
source ./intelli-space/spacemacs/windows.vim
source ./intelli-space/spacemacs/spacemacs/ui-toogles-themes.vim
source ./intelli-space/spacemacs/spacemacs/text.vim
source ./intelli-space/spacemacs/spacemacs/zoom.vim
